sudo: false
cache:
  directories:
  - $HOME/.m2
language: java
script:
- '[ "${TRAVIS_PULL_REQUEST}" != "false" ] || mvn --settings .settings.xml deploy
  -DaltSnapshotDeploymentRepository=repo.spring.io::default::https://repo.spring.io/libs-snapshot-local
  -P release -nsu -Dmaven.test.redirectTestOutputToFile=true'
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] || mvn --settings .settings.xml install
  -nsu -Dmaven.test.redirectTestOutputToFile=true'
env:
  global:
  - GIT_NAME="Roy Clarkson"
  - GIT_EMAIL=rclarkson@pivotal.io
  - CI_DEPLOY_USERNAME=buildmaster
  - secure: HvO/c5ytqcO2kccGdNsZ16cGSl+9Z2kgwpaocxZXQvk9WDUE1gnMyTgPH/UsPwRHNBqAl6kRGjzQbddf5QU0pB/zHKud+zqfBZuA1vLEMSgMCUQtQEk4Avw5weuk7KVk6SlEasH4crOL0+YuBLMQlGR3J85zYW902TGoiuYHAhr4h634+E3mYY20TsjQ1Gv49yuoO3/VRzYxQ17Cg8RJcR9uFkKD5xKK8BfaGUuYEcGREqTwzwOFgfOFoD1qLykeJX2zaeVgz3tUxLtnnGuKVEmZQtMUFUQlumB5dp1ertcBr48wy+rTScZShWfyCXyFbo82xoRs97Qzwk688OGFSDcwT12lftG0Fawa0BTdgdTO5QnjI495TS3oKkwzxnERWKjiB/BWuLil6030E2oupVfSmhIlzQAob06m+nE/S/yLuO7Gs058K3pDyS2Kpf5AFVcj1qKq/2SoqKO27dfJaHwIDMSylQzGMsNy+beCDJEhkaDHhfB0+dYu1WS/kbvT/HLd4DeQkN5fp08PQDBmoJu0cHegXMqIMHTdbIXoInswT1N08ptCz7cyZayFxHWHSdaoInuII0HOb0wRP8yuMZibjmwZBkerlXyEiYejpMZAaZYNZ3L6RMOaR9vL/U3LeHYlLadfjEOfOkiDf9m0LkOMgEMLUInvKROd64Uq+eo=
